### ISSUE TITLE
Mark transitions with `!` sigil.

### ISSUE THREAD

**Issue by cowboyd** [cowboyd/ember-microstates#30]
```
{{boolean.toggle!}}
{{object.put! "key" value}}
```

**Comment by taras** [comment]
I tried `!` and the compiler blows up 😢 
<img width="426" alt="screen shot 2016-10-17 at 9 46 25 pm" src="https://cloud.githubusercontent.com/assets/74687/19461525/3897c472-94b3-11e6-8580-f8c272efd9f7.png">

**Comment by cowboyd** [comment]
Boooo!
