### ISSUE TITLE
Make `Select` state directly enumerable.

### ISSUE THREAD

**Issue by cowboyd** [cowboyd/ember-microstates#39]
Currently, in order to iterate a selection, you have to `each` over the options:

```handlebars
{{let cars=(Select (array mustang camaro corvette))}}

{{#each cars.options as |car|}}
  {{car.value}}: {{car.isSelected}}
{{/each}}
```

But this is pretty much always what you want to do, so would it make sense to just implement `forEach` directly on the select model? That way you can leave off the `.options`

```handlebars
{{#each cars as |car|}}
  {{car.value}}: {{car.isSelected}}
{{/each}}
```

**Comment by taras** [comment]
Yes, this sounds like a good idea. What would that look like?

**Comment by cowboyd** [comment]
I think it's as simple as implementing `forEach` on the selection prototype.

**Comment by taras** [comment]
Ok, I'll give it a try.
