### ISSUE TITLE
Remove `recompute` action

### ISSUE THREAD

**Issue by cowboyd** [cowboyd/ember-microstates#43]
Now that we have `set`, and we understand that the general form of a microstate is `(Microstate value options)` we don't have the need for this to be an action. If custom initialization needs to be handled, it should be done in a method like `construct`, `initialize`, `recomputeState`, etc...

**Comment by taras** [comment]
What about a reset transition that transitions the microstate into value that's initialized from passed in arguments?

**Comment by cowboyd** [comment]
I think that can wait until a subsequent release. We don't have any functionality that depends on this.

**Comment by taras** [comment]
Do you want to remove `recompute` before 0.3.0?

**Comment by cowboyd** [comment]
I think we should since it's currently a public api that is callable from the templates.
