### ISSUE TITLE
Should we rename `on-state` action to `on-transition`?

### ISSUE THREAD

**Issue by taras** [cowboyd/ember-microstates#51]
`state` is a very loaded word. `on-transition` seems to be clearer that it's fired when any transition is triggered rather than when the state changes. Thoughts?

**Comment by cowboyd** [comment]
This sounds good to me. The only thing is that it is much more verbose.

**Comment by taras** [comment]
True. How common is it to listen to every transition in a microstate? It seems like it might be something that might be more common in an addon than the app. Thoughts?

**Comment by cowboyd** [comment]
Yeah, it's probably less likely, and eliminating ambiguity is always a ➕ 

It would also rule out a transition named `transition`, but that also seems unlikely.

I like this idea.

**Comment by taras** [comment]
This action shouldn't be used very often - I think

-- 
Taras Mankovski
