### ISSUE TITLE
best way to get value of `number` in template?

### ISSUE THREAD

**Issue by zigahertz** [cowboyd/ember-microstates#9]
Hi - very nice library!

I am wondering how to best interact with a number microstate in terms of getting its value - here's an example:

```hbs
{{#bind (number 1) as |idx|}}

  {{link-to 'visit and increment' 'some-dynamic-route' idx click=(action idx.add 1)}}

{{/bind}}
```

However, this throws `Uncaught TypeError: Number.prototype.valueOf is not generic`.

If I modify this code using the `ember-composable-helpers` library like

```hbs
{{#bind (number 1) as |idx|}}

  {{link-to 'visit and increment' 'some-dynamic-route' (compute idx.toString) click=(action idx.add 1)}}

{{/bind}}
```

This begins to work, and I'm subsequently using `(compute idx.toString)` other places within the template - but this doesn't seem quite right to me. Is there a better way to do this?

**Comment by cowboyd** [comment]
This is definitely a bug. We had to do this with `String`, and it looks like we'll probably have to do it with Number as well.

**Comment by cowboyd** [comment]
@zigahertz Please let me know if this doesn't solve your issue!

**Comment by zigahertz** [comment]
@cowboyd this is perfect, thanks! I am cloning from the latest SHA on master, will point to the new version whenever you publish it.
